# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(598, 454)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_upload = QtWidgets.QPushButton(self.centralwidget)
        self.btn_upload.setObjectName("btn_upload")
        self.horizontalLayout.addWidget(self.btn_upload)
        self.btn_copy = QtWidgets.QPushButton(self.centralwidget)
        self.btn_copy.setObjectName("btn_copy")
        self.horizontalLayout.addWidget(self.btn_copy)
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.spin_delay = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_delay.sizePolicy().hasHeightForWidth())
        self.spin_delay.setSizePolicy(sizePolicy)
        self.spin_delay.setObjectName("spin_delay")
        self.gridLayout_2.addWidget(self.spin_delay, 4, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(9)
        self.line.setMidLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 2)
        self.btn_take_screenshot = QtWidgets.QPushButton(self.centralwidget)
        self.btn_take_screenshot.setObjectName("btn_take_screenshot")
        self.gridLayout_2.addWidget(self.btn_take_screenshot, 1, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.combo_capture_mode = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_capture_mode.sizePolicy().hasHeightForWidth())
        self.combo_capture_mode.setSizePolicy(sizePolicy)
        self.combo_capture_mode.setObjectName("combo_capture_mode")
        self.combo_capture_mode.addItem("")
        self.combo_capture_mode.addItem("")
        self.combo_capture_mode.addItem("")
        self.gridLayout_2.addWidget(self.combo_capture_mode, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1)
        self.preview_widget = PreviewWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_widget.sizePolicy().hasHeightForWidth())
        self.preview_widget.setSizePolicy(sizePolicy)
        self.preview_widget.setObjectName("preview_widget")
        self.gridLayout_2.addWidget(self.preview_widget, 0, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_take_screenshot, self.combo_capture_mode)
        MainWindow.setTabOrder(self.combo_capture_mode, self.spin_delay)
        MainWindow.setTabOrder(self.spin_delay, self.btn_upload)
        MainWindow.setTabOrder(self.btn_upload, self.btn_copy)
        MainWindow.setTabOrder(self.btn_copy, self.btn_save)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_upload.setText(_translate("MainWindow", "Upload to Imgur"))
        self.btn_copy.setText(_translate("MainWindow", "Copy to clipboard"))
        self.btn_save.setText(_translate("MainWindow", "Save as..."))
        self.label.setText(_translate("MainWindow", "Capture mode"))
        self.btn_take_screenshot.setText(_translate("MainWindow", "Take a New Screenshot"))
        self.combo_capture_mode.setItemText(0, _translate("MainWindow", "Full Screen"))
        self.combo_capture_mode.setItemText(1, _translate("MainWindow", "Window Under Cursor"))
        self.combo_capture_mode.setItemText(2, _translate("MainWindow", "Current Screen"))
        self.label_2.setText(_translate("MainWindow", "Screenshot delay"))

from preview_widget import PreviewWidget
